import type { Artist, MediaAsset, VideoTemplate } from "../types/index.js";

export const MOCK_ARTISTS: Artist[] = [
  {
    id: "2z",
    name: "2Z",
    country: "韩国",
    type: "K-rock / K-pop Band / Fashion Band",
    fanName: "FromA",
    operationFocus: ["虚拟 IP", "全球演出", "社交媒体增长", "粉丝社群互动"],
    keywords: ["high fashion band", "Korean rock energy", "global fans", "virtual IP", "backstage story", "live performance"],
    knowledgeModules: [
      { id: "2z_basic", name: "基础资料", description: "艺人基本信息、成员介绍", content: "2Z 是来自韩国的时尚摇滚乐队，以高端时尚造型和强烈的现场能量著称，拥有全球粉丝群体 FromA。" },
      { id: "2z_music", name: "音乐作品与风格", description: "代表作品、音乐风格", content: "融合 K-rock 与 K-pop 元素，代表作包括《Neon Pulse》《Digital Stage》等，风格兼具时尚感与摇滚能量。" },
      { id: "2z_social", name: "社交媒体内容", description: "近期社媒动态", content: "活跃于 Instagram、TikTok，定期发布幕后花絮、时尚大片和粉丝互动内容。" },
      { id: "2z_backstage", name: "幕后故事", description: "创作过程与幕后花絮", content: "乐队成员分享录音室日常、排练花絮和全球巡演幕后故事。" },
      { id: "2z_fan", name: "粉丝互动", description: "粉丝活动与互动记录", content: "FromA 粉丝群体遍布全球，定期举办线上粉丝见面会和创意应援活动。" },
      { id: "2z_platform", name: "平台活动", description: "CisuMusic 平台活动", content: "参与 CisuMusic Web3 音乐平台独家发行活动，发布限量 NFT 音乐作品。" },
      { id: "2z_assets", name: "图片素材", description: "官方图片素材库", content: "包含官方宣传照、演出现场照、时尚大片等高清素材。" },
      { id: "2z_risk", name: "风险提示", description: "禁用内容与注意事项", content: "禁止使用未授权的粉丝创作内容；避免涉及成员私生活；不得使用竞品平台 Logo。" },
    ],
  },
  {
    id: "minh",
    name: "MINH",
    country: "越南",
    type: "Pop / R&B",
    operationFocus: ["短剧内容", "AI 视频", "粉丝增长", "社交媒体传播"],
    keywords: ["emotional pop", "Vietnamese artist", "short drama", "cinematic storytelling", "fan connection"],
    knowledgeModules: [
      { id: "minh_basic", name: "基础资料", description: "艺人基本信息", content: "MINH 是越南新生代 Pop/R&B 歌手，以情感细腻的歌声和电影感 MV 著称。" },
      { id: "minh_music", name: "音乐作品与风格", description: "代表作品", content: "代表作《Cảm Xúc》《Mưa Đêm》，风格融合越南流行与 R&B 元素。" },
      { id: "minh_social", name: "社交媒体内容", description: "社媒动态", content: "活跃于 TikTok 和 YouTube，短剧内容获得大量传播。" },
      { id: "minh_backstage", name: "幕后故事", description: "创作故事", content: "MINH 亲自参与词曲创作，分享情感创作背后的故事。" },
      { id: "minh_fan", name: "粉丝互动", description: "粉丝活动", content: "与粉丝保持密切互动，定期发布粉丝专属内容。" },
      { id: "minh_platform", name: "平台活动", description: "平台活动", content: "在 CisuMusic 平台发布独家单曲和幕后花絮。" },
      { id: "minh_assets", name: "图片素材", description: "素材库", content: "电影感写真、MV 截图、演出照片。" },
      { id: "minh_risk", name: "风险提示", description: "注意事项", content: "避免使用未授权的个人照片；不得涉及感情话题。" },
    ],
  },
  {
    id: "nghich",
    name: "Nghịch",
    country: "越南",
    type: "Punk Rock / Indie Rock",
    operationFocus: ["年轻人文化", "现场演出", "社群传播", "音乐态度表达"],
    keywords: ["punk rock", "youth culture", "indie scene", "raw live energy", "rebellious style"],
    knowledgeModules: [
      { id: "nghich_basic", name: "基础资料", description: "艺人基本信息", content: "Nghịch 是越南朋克摇滚乐队，以叛逆的音乐态度和激烈的现场演出著称。" },
      { id: "nghich_music", name: "音乐作品与风格", description: "代表作品", content: "代表作《Nổi Loạn》《Phá Vỡ》，风格粗粝有力，充满年轻人的反叛精神。" },
      { id: "nghich_social", name: "社交媒体内容", description: "社媒动态", content: "在 Facebook 和 YouTube 发布现场演出视频和音乐态度宣言。" },
      { id: "nghich_backstage", name: "幕后故事", description: "创作故事", content: "乐队分享地下音乐场景的成长故事和创作理念。" },
      { id: "nghich_fan", name: "粉丝互动", description: "粉丝活动", content: "与本地独立音乐社群保持紧密联系。" },
      { id: "nghich_platform", name: "平台活动", description: "平台活动", content: "在 CisuMusic 平台发布独立专辑。" },
      { id: "nghich_assets", name: "图片素材", description: "素材库", content: "现场演出照、街头风格写真。" },
      { id: "nghich_risk", name: "风险提示", description: "注意事项", content: "避免过度商业化内容；保持独立音乐人形象。" },
    ],
  },
  {
    id: "vtv",
    name: "Vũ Thanh Vân",
    country: "越南",
    type: "Indie Pop / Alternative",
    operationFocus: ["粉丝俱乐部", "艺人故事", "内容沉淀", "深度社群"],
    keywords: ["indie pop", "poetic mood", "fan club", "emotional storytelling", "soft cinematic"],
    knowledgeModules: [
      { id: "vtv_basic", name: "基础资料", description: "艺人基本信息", content: "Vũ Thanh Vân 是越南独立流行女歌手，以诗意的歌词和柔美的电影感 MV 著称。" },
      { id: "vtv_music", name: "音乐作品与风格", description: "代表作品", content: "代表作《Giấc Mơ》《Mùa Thu》，风格温柔细腻，充满诗意。" },
      { id: "vtv_social", name: "社交媒体内容", description: "社媒动态", content: "在 Instagram 和 YouTube 发布生活日记和音乐故事。" },
      { id: "vtv_backstage", name: "幕后故事", description: "创作故事", content: "分享创作灵感、生活感悟和音乐背后的情感故事。" },
      { id: "vtv_fan", name: "粉丝互动", description: "粉丝活动", content: "拥有深度粉丝俱乐部，定期举办线上音乐分享会。" },
      { id: "vtv_platform", name: "平台活动", description: "平台活动", content: "在 CisuMusic 平台发布独家 EP 和粉丝专属内容。" },
      { id: "vtv_assets", name: "图片素材", description: "素材库", content: "柔美写真、自然风光、生活日记照片。" },
      { id: "vtv_risk", name: "风险提示", description: "注意事项", content: "保持温柔艺人形象；避免过于商业化的内容风格。" },
    ],
  },
];

export const MOCK_ASSETS: MediaAsset[] = [
  { id: "a001", name: "2Z 官方宣传照 2024", type: "artist_photo", url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400", tags: ["2Z", "官方", "2024"], artistId: "2z", licensed: true, description: "2024年官方宣传照" },
  { id: "a002", name: "2Z 演出现场照", type: "performance_photo", url: "https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=400", tags: ["2Z", "演出", "现场"], artistId: "2z", licensed: true, description: "首尔演唱会现场照" },
  { id: "a003", name: "MINH 写真集", type: "artist_photo", url: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400", tags: ["MINH", "写真"], artistId: "minh", licensed: true, description: "电影感写真" },
  { id: "a004", name: "CisuMusic Logo", type: "platform_logo", url: "https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=400", tags: ["CisuMusic", "Logo", "品牌"], licensed: true, description: "CisuMusic 官方 Logo" },
  { id: "a005", name: "App 截图 - 首页", type: "app_screenshot", url: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400", tags: ["App", "截图", "UI"], licensed: true, description: "CisuMusic App 首页截图" },
  { id: "a006", name: "粉丝应援现场", type: "fan_screenshot", url: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400", tags: ["粉丝", "应援", "现场"], licensed: true, description: "粉丝应援活动现场" },
  { id: "a007", name: "Nghịch 街头写真", type: "artist_photo", url: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400", tags: ["Nghịch", "街头", "朋克"], artistId: "nghich", licensed: true, description: "街头风格写真" },
  { id: "a008", name: "Vũ Thanh Vân 自然写真", type: "artist_photo", url: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400", tags: ["VTV", "自然", "柔美"], artistId: "vtv", licensed: true, description: "自然风光写真" },
  { id: "a009", name: "Web3 NFT 素材", type: "virtual_ip", url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400", tags: ["Web3", "NFT", "虚拟"], licensed: true, description: "Web3 NFT 艺术素材" },
  { id: "a010", name: "社交媒体截图", type: "social_screenshot", url: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=400", tags: ["社交", "截图", "互动"], licensed: true, description: "社交媒体互动截图" },
];

export const MOCK_TEMPLATES: VideoTemplate[] = [
  {
    templateId: "tpl_new_song",
    name: "新歌发布预告",
    description: "专为新歌发布设计，突出歌曲亮点和艺人魅力，制造期待感",
    suitableRoles: ["operator", "content_editor"],
    suitableGoals: ["new_song"],
    recommendedDuration: 30,
    recommendedPlatforms: ["tiktok", "instagram_reels", "douyin"],
    defaultStyle: "cyber_music",
    defaultStructure: "开场悬念 → 艺人登场 → 歌曲片段 → CTA",
    defaultCTA: "点击链接收听完整版 | 关注艺人获取首发通知",
    defaultPromptStyle: "cinematic music promo, neon lights, dramatic reveal",
  },
  {
    templateId: "tpl_concert",
    name: "演出倒计时",
    description: "演出前宣传视频，营造现场氛围，激发粉丝期待",
    suitableRoles: ["operator", "fan_operator"],
    suitableGoals: ["concert_promo"],
    recommendedDuration: 30,
    recommendedPlatforms: ["tiktok", "instagram_reels", "xiaohongshu"],
    defaultStyle: "cinematic",
    defaultStructure: "倒计时开场 → 演出精彩片段 → 票务信息 → CTA",
    defaultCTA: "立即购票 | 现在预约",
    defaultPromptStyle: "concert atmosphere, crowd energy, stage lights",
  },
  {
    templateId: "tpl_artist_intro",
    name: "艺人故事介绍",
    description: "深度介绍艺人背景、音乐理念和个人故事",
    suitableRoles: ["content_editor", "operator"],
    suitableGoals: ["artist_intro"],
    recommendedDuration: 60,
    recommendedPlatforms: ["youtube_shorts", "xiaohongshu", "shipinhao"],
    defaultStyle: "documentary",
    defaultStructure: "艺人登场 → 音乐故事 → 代表作品 → 艺人理念 → 关注引导",
    defaultCTA: "关注艺人 | 了解更多",
    defaultPromptStyle: "documentary style, intimate portrait, warm lighting",
  },
  {
    templateId: "tpl_fan_support",
    name: "粉丝应援视频",
    description: "面向粉丝的互动视频，增强粉丝归属感和社群凝聚力",
    suitableRoles: ["fan_operator"],
    suitableGoals: ["fan_interaction"],
    recommendedDuration: 30,
    recommendedPlatforms: ["tiktok", "xiaohongshu", "douyin"],
    defaultStyle: "fan_support",
    defaultStructure: "粉丝应援开场 → 艺人互动片段 → 粉丝留言 → 应援口号",
    defaultCTA: "加入粉丝团 | 一起应援",
    defaultPromptStyle: "fan celebration, colorful lights, energetic crowd",
  },
  {
    templateId: "tpl_backstage",
    name: "幕后花絮",
    description: "展示艺人幕后工作状态，增加真实感和亲近感",
    suitableRoles: ["content_editor", "fan_operator"],
    suitableGoals: ["backstage"],
    recommendedDuration: 60,
    recommendedPlatforms: ["youtube_shorts", "instagram_reels", "xiaohongshu"],
    defaultStyle: "documentary",
    defaultStructure: "幕后场景 → 工作状态 → 艺人分享 → 预告下期",
    defaultCTA: "订阅获取更多幕后内容",
    defaultPromptStyle: "behind the scenes, candid moments, studio atmosphere",
  },
  {
    templateId: "tpl_app_promo",
    name: "App 活动推广",
    description: "推广 CisuMusic App 特定活动或功能",
    suitableRoles: ["operator"],
    suitableGoals: ["app_promo"],
    recommendedDuration: 30,
    recommendedPlatforms: ["tiktok", "douyin", "instagram_reels"],
    defaultStyle: "cyber_music",
    defaultStructure: "活动亮点 → App 功能展示 → 奖励说明 → 下载 CTA",
    defaultCTA: "立即下载 CisuMusic | 参与活动赢奖励",
    defaultPromptStyle: "app interface mockup, digital rewards, modern UI",
  },
  {
    templateId: "tpl_web3",
    name: "Web3 奖励活动",
    description: "介绍 Web3 音乐 NFT 或 Token 奖励活动",
    suitableRoles: ["operator", "content_editor"],
    suitableGoals: ["web3_nft"],
    recommendedDuration: 60,
    recommendedPlatforms: ["x", "youtube_shorts", "instagram_reels"],
    defaultStyle: "cyber_music",
    defaultStructure: "Web3 概念引入 → NFT 展示 → 奖励机制 → 参与方式 → CTA",
    defaultCTA: "立即参与 | 获取限量 NFT",
    defaultPromptStyle: "blockchain visualization, NFT art, futuristic digital world",
  },
  {
    templateId: "tpl_virtual_ip",
    name: "虚拟 IP 出道预告",
    description: "虚拟艺人或数字 IP 的出道宣传视频",
    suitableRoles: ["operator", "content_editor"],
    suitableGoals: ["virtual_ip"],
    recommendedDuration: 60,
    recommendedPlatforms: ["tiktok", "youtube_shorts", "douyin"],
    defaultStyle: "metaverse_stage",
    defaultStructure: "神秘开场 → IP 形象揭晓 → 能力展示 → 互动预告 → 关注 CTA",
    defaultCTA: "关注虚拟 IP | 参与互动",
    defaultPromptStyle: "virtual avatar, holographic stage, metaverse environment",
  },
];
